### ISSUE TITLE
Khi booking đã có chuyến thì popup đặt chuyến hiển thị sai

### ISSUE THREAD

**Issue by JustinBeBoy** [JustinBeBoy/admin_kethop_v2#14]
Khi có cuộc gọi đến mà booking đó đã có chuyến thì đã hiển thị lable đã có chuyến nhưng thông tin chuyến không có nhưng không hiển thị, kiểm tra lại design

![image](https://user-images.githubusercontent.com/19331824/221339626-b15bf10a-bcd3-4118-b096-863c9e928054.png)

**Comment by duclv92** [comment]
@JustinBeBoy api map trả thêm driver_phone, driver_name để hiển thị khi chọn cho api map và socket tracking
