### ISSUE TITLE
Tạo chuyến với type gửi hàng đang không hiển thị trên list, có thể do seats = 0

### ISSUE THREAD

**Issue by duclv92** [JustinBeBoy/admin_kethop_v2#6]

**Comment by JustinBeBoy** [comment]
bịp anh tạo được này
![image](https://user-images.githubusercontent.com/19331824/220654635-3beaabb7-ca72-4f41-9a7a-040082b0678d.png)

**Comment by JustinBeBoy** [comment]
không tái hiện được
