### ISSUE TITLE
Đang không lọc chuyến booking đó đã thuộc về

### ISSUE THREAD

**Issue by JustinBeBoy** [JustinBeBoy/admin_kethop_v2#9]
booking ở dứoi thuộc chuyến 14 nhưng ở popup đổi chuyến vẫn hiển thị chuyến số 14
lọc cái chuyến mà booking đó đang ở đi nhé

![image](https://user-images.githubusercontent.com/19331824/220578378-2b9e9df1-ad82-4df1-b580-dfa59ad123e4.png)

**Comment by duclv92** [comment]
api bịp, toàn bắt client check, có ngày bị leak api lỗi hết. hệ thống :)))

**Comment by duclv92** [comment]
@JustinBeBoy

**Comment by JustinBeBoy** [comment]
đang dùng chung api mà
